[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.7.0", default-features = false }
bevy-discord-presence = { version = "0.3.0", path = "../../crates/bevy" }
