[package]
name = "discord_presence_subscriber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord-presence = { version = "0.5.2", path = "../../crates/rpc" }
