[package]
authors = ["Patrick Auernig <dev.patrick.auernig@gmail.com>"]
name    = "discord-presence"
version = "0.0.0"

[dependencies]
simplelog = "~0.5"

[dependencies.discord-rpc-client]
path = "../../"
