[package]
name = "bevy-discord-presence"
description = "Discord presence plugin for the Bevy game engine"
license = "MIT"
authors = ["Juliette Cordor"]
keywords = ["discord", "rpc", "ipc"]
version = "0.2.0"
repository  = "https://github.com/jewlexx/discord-presence.git"
edition = "2021"

[dependencies]
discord-presence = "0.5.0"
bevy = { version = "0.8.0-dev", git = "https://github.com/bevyengine/bevy", rev="26c3b20f1ce1e04fcd37816d35fdff4d8433064f", default-features = false }

[dev-dependencies]
version-sync = "0.9.4"
