[package]
name = "bevy-discord-presence"
description = "Discord presence plugin for the Bevy game engine"
license = "MIT"
author = "Juliette Cordor"
version = "0.1.0"
edition = "2021"

[dependencies]
discord-presence = "0.4.2"
serde_json = "1.0.79"
bevy = "0.7.0"
